### ISSUE TITLE
Error thrown on transport instantiation

### ISSUE THREAD

**Issue by Tzrlk** [juttle/winston-logrotate#2]
I've set up my logger to instantiate the transport like so:
```js
const winston = require('winston');
require('winston-logrotate');

winston.add(new winston.transports.Rotate({ file: `${__dirname}/console.log` }));
```

Unfortunately, executing the program causes it to fail with the following error:
```
C:\code\backup-scripts\index.js:25
winston.add(new winston.transports.Rotate({ file: `${__dirname}/console.log` }));
            ^

TypeError: winston.transports.Rotate is not a constructor
    at Object.<anonymous> (C:\code\backup-scripts\index.js:25:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3
```

For some reason, at the time that the `winston.add` line is executed, `winston.transports.Rotate` is undefined, though its is defined perfectly fine when setting it in `winston-logrotate.js`.

My running theory is that it's adding itself to a different winston instantiation, and subsuming that with something like proxyquire should make that evident. Not sure how to fix the actual problem, however.

**Comment by Tzrlk** [comment]
Proxyquire did indeed fix the issue:
```js
const proxyquire = require('proxyquire');
const winston = require('winston');
proxyquire('winston-logrotate', {
	winston: winston
});

winston.add(winston.transports.Rotate, { file: `${__dirname}/console.log` });
```

Note the different invocation of `winston.add` as well. Should probably update that on the README.

**Comment by ticapix** [comment]
Indeed, it would be nice to update the README and dependency list with proxyquire

**Comment by qbradq** [comment]
This same issue is preventing winston-logrotate from working correctly under Istanbul coverage inspection. Can you just export the constructor as well?

**Comment by lukebarnard1** [comment]
One can easily use it without making `winston-logrotate` part of `winston` itself:
```js
const winston = require('winston');
const Rotate = require('winston-logrotate').Rotate;
...
transports.push(new Rotate(logrotateConfig));
...
log = new winston.Logger({
  transports: transports,
});
```

**Comment by jcramirez** [comment]
Thanks @lukebarnard1! that totally fixed my issue

**Comment by motigra** [comment]
I'm using `Winston 2.3.1` and none of the above worked for me, but this did:

```javascript
var winston = require('winston');
var Rotate = require('winston-logrotate').Rotate;

winston.add(Rotate, {
    file: './log.txt', // this path needs to be absolute
    colorize: false,
    timestamp: true,
    json: false,
    size: '100',
    keep: 5,
    compress: false
});
```
Maybe someone else will find it helpful, but the docs on this should really be updated.

**Comment by obermillerk** [comment]
The issue with the above workarounds (using the Rotate prototype separately) is that they still reference the internal winston version.  This can lead to unexpected differences in behavior between this and standard transports.  This whole issue is created by the winston dependency for this library being restricted to a specific version rather than >=, as in #6.  If you aren't using the exact version for this library, it will install winston again in a sub-directory, and use that for everything.  If you use the "correct" version or change the package.json for this library to have a '^' before the winston version, you'll find that you can use it as expected (winston.transports.Rotate).
